// Code generated by xgen. DO NOT EDIT.

package xiidm

import (
	"encoding/xml"
)

// NonEmptyString ...
type NonEmptyString string

// Extension ...
type Extension struct {
	XMLName xml.Name `xml:"extension"`
	IdAttr  string   `xml:"id,attr"`
}

// Network ...
type Network struct {
	IdAttr                     string                     `xml:"id,attr"`
	CaseDateAttr               string                     `xml:"caseDate,attr"`
	ForecastDistanceAttr       int                        `xml:"forecastDistance,attr"`
	SourceFormatAttr           string                     `xml:"sourceFormat,attr"`
	MinimumValidationLevelAttr string                     `xml:"minimumValidationLevel,attr"`
	Alias                      []Alias                    `xml:"alias"`
	Property                   []Property                 `xml:"property"`
	Network                    []Network                  `xml:"network"`
	DcNode                     []DcNode                   `xml:"dcNode"`
	DcSwitch                   []DcSwitch                 `xml:"dcSwitch"`
	DcGround                   []DcGround                 `xml:"dcGround"`
	DcLine                     []DcLine                   `xml:"dcLine"`
	VoltageLevel               []VoltageLevel             `xml:"voltageLevel"`
	Substation                 []Substation               `xml:"substation"`
	TwoWindingsTransformer     []TwoWindingsTransformer   `xml:"twoWindingsTransformer"`
	ThreeWindingsTransformer   []ThreeWindingsTransformer `xml:"threeWindingsTransformer"`
	Line                       []Line                     `xml:"line"`
	TieLine                    []TieLine                  `xml:"tieLine"`
	HvdcLine                   []HvdcLine                 `xml:"hvdcLine"`
	VoltageAngleLimit          []VoltageAngleLimit        `xml:"voltageAngleLimit"`
	Area                       []Area                     `xml:"area"`
	Extension                  []Extension                `xml:"extension"`
}

// Identifiable ...
type Identifiable struct {
	IdAttr         string     `xml:"id,attr"`
	NameAttr       string     `xml:"name,attr,omitempty"`
	FictitiousAttr bool       `xml:"fictitious,attr,omitempty"`
	Alias          []Alias    `xml:"alias"`
	Property       []Property `xml:"property"`
}

// Alias ...
type Alias struct {
	TypeAttr string `xml:"type,attr,omitempty"`
	Value    string `xml:",chardata"`
}

// Property ...
type Property struct {
	NameAttr  string `xml:"name,attr"`
	ValueAttr string `xml:"value,attr"`
}

// Substation ...
type Substation struct {
	TsoAttr                  string                     `xml:"tso,attr,omitempty"`
	CountryAttr              string                     `xml:"country,attr,omitempty"`
	GeographicalTagsAttr     string                     `xml:"geographicalTags,attr,omitempty"`
	VoltageLevel             []VoltageLevel             `xml:"voltageLevel"`
	TwoWindingsTransformer   []TwoWindingsTransformer   `xml:"twoWindingsTransformer"`
	ThreeWindingsTransformer []ThreeWindingsTransformer `xml:"threeWindingsTransformer"`
	OverloadManagementSystem []OverloadManagementSystem `xml:"overloadManagementSystem"`
	*Identifiable
}

// TopologyKind ...
type TopologyKind string

// VoltageLevel ...
type VoltageLevel struct {
	NominalVAttr            float64                   `xml:"nominalV,attr"`
	TopologyKindAttr        string                    `xml:"topologyKind,attr"`
	LowVoltageLimitAttr     float64                   `xml:"lowVoltageLimit,attr,omitempty"`
	HighVoltageLimitAttr    float64                   `xml:"highVoltageLimit,attr,omitempty"`
	NodeBreakerTopology     *NodeBreakerTopology      `xml:"nodeBreakerTopology"`
	BusBreakerTopology      *BusBreakerTopology       `xml:"busBreakerTopology"`
	Generator               []Generator               `xml:"generator"`
	Battery                 []Battery                 `xml:"battery"`
	Load                    []Load                    `xml:"load"`
	ShuntCompensator        []ShuntCompensator        `xml:"shuntCompensator"`
	DanglingLine            []DanglingLine            `xml:"danglingLine"`
	StaticVarCompensator    []StaticVarCompensator    `xml:"staticVarCompensator"`
	VscConverterStation     []VscConverterStation     `xml:"vscConverterStation"`
	LccConverterStation     []LccConverterStation     `xml:"lccConverterStation"`
	VoltageSourceConverter  []VoltageSourceConverter  `xml:"voltageSourceConverter"`
	LineCommutatedConverter []LineCommutatedConverter `xml:"lineCommutatedConverter"`
	Ground                  []Ground                  `xml:"ground"`
	*Identifiable
}

// NodeBreakerTopology ...
type NodeBreakerTopology struct {
	BusbarSection      []BusbarSection       `xml:"busbarSection"`
	Switch             []SwitchNode          `xml:"switch"`
	InternalConnection []InternalConnection  `xml:"internalConnection"`
	Bus                []CalculatedBus       `xml:"bus"`
	Inj                []FictitiousInjection `xml:"inj"`
}

// BusBreakerTopology ...
type BusBreakerTopology struct {
	Bus    []Bus       `xml:"bus"`
	Switch []SwitchBus `xml:"switch"`
}

// Bus ...
type Bus struct {
	VAttr            float64 `xml:"v,attr,omitempty"`
	AngleAttr        float64 `xml:"angle,attr,omitempty"`
	FictitiousP0Attr float64 `xml:"fictitiousP0,attr,omitempty"`
	FictitiousQ0Attr float64 `xml:"fictitiousQ0,attr,omitempty"`
	*Identifiable
}

// BusbarSection ...
type BusbarSection struct {
	NodeAttr int `xml:"node,attr"`
	*Identifiable
}

// CalculatedBus ...
type CalculatedBus struct {
	NodesAttr string     `xml:"nodes,attr"`
	VAttr     float64    `xml:"v,attr,omitempty"`
	AngleAttr float64    `xml:"angle,attr,omitempty"`
	Property  []Property `xml:"property"`
}

// FictitiousInjection ...
type FictitiousInjection struct {
	NodeAttr         int     `xml:"node,attr"`
	FictitiousP0Attr float64 `xml:"fictitiousP0,attr,omitempty"`
	FictitiousQ0Attr float64 `xml:"fictitiousQ0,attr,omitempty"`
}

// SwitchKind ...
type SwitchKind string

// Switch ...
type Switch struct {
	KindAttr     string `xml:"kind,attr"`
	RetainedAttr bool   `xml:"retained,attr"`
	OpenAttr     bool   `xml:"open,attr"`
	*Identifiable
}

// SwitchNode ...
type SwitchNode struct {
	Node1Attr int `xml:"node1,attr"`
	Node2Attr int `xml:"node2,attr"`
	*Switch
}

// SwitchBus ...
type SwitchBus struct {
	Bus1Attr string `xml:"bus1,attr"`
	Bus2Attr string `xml:"bus2,attr"`
	*Switch
}

// InternalConnection ...
type InternalConnection struct {
	Node1Attr int `xml:"node1,attr"`
	Node2Attr int `xml:"node2,attr"`
}

// Point ...
type Point struct {
	PAttr    float64 `xml:"p,attr"`
	MinQAttr float64 `xml:"minQ,attr"`
	MaxQAttr float64 `xml:"maxQ,attr"`
}

// ReactiveCapabilityCurve ...
type ReactiveCapabilityCurve struct {
	Point []Point `xml:"point"`
}

// MinMaxReactiveLimits ...
type MinMaxReactiveLimits struct {
	MinQAttr float64 `xml:"minQ,attr"`
	MaxQAttr float64 `xml:"maxQ,attr"`
}

// EnergySource ...
type EnergySource string

// Injection ...
type Injection struct {
	NodeAttr           int     `xml:"node,attr,omitempty"`
	BusAttr            string  `xml:"bus,attr,omitempty"`
	ConnectableBusAttr string  `xml:"connectableBus,attr,omitempty"`
	PAttr              float64 `xml:"p,attr,omitempty"`
	QAttr              float64 `xml:"q,attr,omitempty"`
	*Identifiable
}

// Generator ...
type Generator struct {
	EnergySourceAttr           string                   `xml:"energySource,attr"`
	MaxPAttr                   float64                  `xml:"maxP,attr"`
	MinPAttr                   float64                  `xml:"minP,attr"`
	RatedSAttr                 float64                  `xml:"ratedS,attr,omitempty"`
	VoltageRegulatorOnAttr     bool                     `xml:"voltageRegulatorOn,attr"`
	TargetPAttr                float64                  `xml:"targetP,attr"`
	TargetQAttr                float64                  `xml:"targetQ,attr,omitempty"`
	TargetVAttr                float64                  `xml:"targetV,attr,omitempty"`
	EquivalentLocalTargetVAttr float64                  `xml:"equivalentLocalTargetV,attr,omitempty"`
	IsCondenserAttr            bool                     `xml:"isCondenser,attr,omitempty"`
	RegulatingTerminal         *TerminalRef             `xml:"regulatingTerminal"`
	ReactiveCapabilityCurve    *ReactiveCapabilityCurve `xml:"reactiveCapabilityCurve"`
	MinMaxReactiveLimits       *MinMaxReactiveLimits    `xml:"minMaxReactiveLimits"`
	*Injection
}

// Battery ...
type Battery struct {
	TargetPAttr             float64                  `xml:"targetP,attr"`
	TargetQAttr             float64                  `xml:"targetQ,attr"`
	MinPAttr                float64                  `xml:"minP,attr"`
	MaxPAttr                float64                  `xml:"maxP,attr"`
	ReactiveCapabilityCurve *ReactiveCapabilityCurve `xml:"reactiveCapabilityCurve"`
	MinMaxReactiveLimits    *MinMaxReactiveLimits    `xml:"minMaxReactiveLimits"`
	*Injection
}

// LoadType ...
type LoadType string

// Load ...
type Load struct {
	P0Attr           float64               `xml:"p0,attr"`
	Q0Attr           float64               `xml:"q0,attr"`
	LoadTypeAttr     string                `xml:"loadType,attr,omitempty"`
	ZipModel         *ZipLoadModel         `xml:"zipModel"`
	ExponentialModel *ExponentialLoadModel `xml:"exponentialModel"`
	*Injection
}

// ZipLoadModel ...
type ZipLoadModel struct {
	C0pAttr float64 `xml:"c0p,attr"`
	C1pAttr float64 `xml:"c1p,attr"`
	C2pAttr float64 `xml:"c2p,attr"`
	C0qAttr float64 `xml:"c0q,attr"`
	C1qAttr float64 `xml:"c1q,attr"`
	C2qAttr float64 `xml:"c2q,attr"`
}

// ExponentialLoadModel ...
type ExponentialLoadModel struct {
	NpAttr float64 `xml:"np,attr"`
	NqAttr float64 `xml:"nq,attr"`
}

// ShuntCompensator ...
type ShuntCompensator struct {
	SectionCountAttr       int                  `xml:"sectionCount,attr"`
	SolvedSectionCountAttr int                  `xml:"solvedSectionCount,attr,omitempty"`
	VoltageRegulatorOnAttr bool                 `xml:"voltageRegulatorOn,attr"`
	TargetVAttr            float64              `xml:"targetV,attr,omitempty"`
	TargetDeadbandAttr     float64              `xml:"targetDeadband,attr,omitempty"`
	ShuntLinearModel       *ShuntLinearModel    `xml:"shuntLinearModel"`
	ShuntNonLinearModel    *ShuntNonLinearModel `xml:"shuntNonLinearModel"`
	RegulatingTerminal     *TerminalRef         `xml:"regulatingTerminal"`
	*Injection
}

// ShuntLinearModel ...
type ShuntLinearModel struct {
	BPerSectionAttr         float64 `xml:"bPerSection,attr"`
	GPerSectionAttr         float64 `xml:"gPerSection,attr,omitempty"`
	MaximumSectionCountAttr int     `xml:"maximumSectionCount,attr"`
}

// ShuntNonLinearModel ...
type ShuntNonLinearModel struct {
	Section []ShuntSection `xml:"section"`
}

// ShuntSection ...
type ShuntSection struct {
	BAttr float64 `xml:"b,attr"`
	GAttr float64 `xml:"g,attr,omitempty"`
}

// TemporaryLimit ...
type TemporaryLimit struct {
	XMLName                xml.Name `xml:"temporaryLimit"`
	NameAttr               string   `xml:"name,attr"`
	AcceptableDurationAttr int      `xml:"acceptableDuration,attr,omitempty"`
	ValueAttr              float64  `xml:"value,attr,omitempty"`
	FictitiousAttr         bool     `xml:"fictitious,attr,omitempty"`
}

// LoadingLimit ...
type LoadingLimit struct {
	PermanentLimitAttr float64          `xml:"permanentLimit,attr,omitempty"`
	TemporaryLimit     []TemporaryLimit `xml:"temporaryLimit"`
}

// OperationalLimitsGroup ...
type OperationalLimitsGroup struct {
	IdAttr              string        `xml:"id,attr"`
	Property            []Property    `xml:"property"`
	ActivePowerLimits   *LoadingLimit `xml:"activePowerLimits"`
	ApparentPowerLimits *LoadingLimit `xml:"apparentPowerLimits"`
	CurrentLimits       *LoadingLimit `xml:"currentLimits"`
}

// DanglingLine ...
type DanglingLine struct {
	SelectedOperationalLimitsGroupIdAttr string                   `xml:"selectedOperationalLimitsGroupId,attr,omitempty"`
	P0Attr                               float64                  `xml:"p0,attr"`
	Q0Attr                               float64                  `xml:"q0,attr"`
	RAttr                                float64                  `xml:"r,attr"`
	XAttr                                float64                  `xml:"x,attr"`
	GAttr                                float64                  `xml:"g,attr"`
	BAttr                                float64                  `xml:"b,attr"`
	GenerationMinPAttr                   float64                  `xml:"generationMinP,attr,omitempty"`
	GenerationMaxPAttr                   float64                  `xml:"generationMaxP,attr,omitempty"`
	GenerationVoltageRegulationOnAttr    bool                     `xml:"generationVoltageRegulationOn,attr,omitempty"`
	GenerationTargetPAttr                float64                  `xml:"generationTargetP,attr,omitempty"`
	GenerationTargetVAttr                float64                  `xml:"generationTargetV,attr,omitempty"`
	GenerationTargetQAttr                float64                  `xml:"generationTargetQ,attr,omitempty"`
	PairingKeyAttr                       string                   `xml:"pairingKey,attr,omitempty"`
	ReactiveCapabilityCurve              *ReactiveCapabilityCurve `xml:"reactiveCapabilityCurve"`
	MinMaxReactiveLimits                 *MinMaxReactiveLimits    `xml:"minMaxReactiveLimits"`
	OperationalLimitsGroup               []OperationalLimitsGroup `xml:"operationalLimitsGroup"`
	*Injection
}

// StaticVarCompensatorRegulationMode ...
type StaticVarCompensatorRegulationMode string

// StaticVarCompensator ...
type StaticVarCompensator struct {
	BMinAttr                  float64      `xml:"bMin,attr"`
	BMaxAttr                  float64      `xml:"bMax,attr"`
	VoltageSetpointAttr       float64      `xml:"voltageSetpoint,attr,omitempty"`
	ReactivePowerSetpointAttr float64      `xml:"reactivePowerSetpoint,attr,omitempty"`
	RegulationModeAttr        string       `xml:"regulationMode,attr"`
	RegulatingAttr            bool         `xml:"regulating,attr"`
	RegulatingTerminal        *TerminalRef `xml:"regulatingTerminal"`
	*Injection
}

// Branch ...
type Branch struct {
	Node1Attr           int     `xml:"node1,attr"`
	Bus1Attr            string  `xml:"bus1,attr,omitempty"`
	ConnectableBus1Attr string  `xml:"connectableBus1,attr,omitempty"`
	VoltageLevelId1Attr string  `xml:"voltageLevelId1,attr"`
	Node2Attr           int     `xml:"node2,attr"`
	Bus2Attr            string  `xml:"bus2,attr,omitempty"`
	ConnectableBus2Attr string  `xml:"connectableBus2,attr,omitempty"`
	VoltageLevelId2Attr string  `xml:"voltageLevelId2,attr"`
	P1Attr              float64 `xml:"p1,attr,omitempty"`
	Q1Attr              float64 `xml:"q1,attr,omitempty"`
	P2Attr              float64 `xml:"p2,attr,omitempty"`
	Q2Attr              float64 `xml:"q2,attr,omitempty"`
	*Identifiable
}

// TwoWindingsTransformer ...
type TwoWindingsTransformer struct {
	SelectedOperationalLimitsGroupId1Attr string                   `xml:"selectedOperationalLimitsGroupId1,attr,omitempty"`
	SelectedOperationalLimitsGroupId2Attr string                   `xml:"selectedOperationalLimitsGroupId2,attr,omitempty"`
	RAttr                                 float64                  `xml:"r,attr"`
	XAttr                                 float64                  `xml:"x,attr"`
	GAttr                                 float64                  `xml:"g,attr"`
	BAttr                                 float64                  `xml:"b,attr"`
	RatedU1Attr                           float64                  `xml:"ratedU1,attr"`
	RatedU2Attr                           float64                  `xml:"ratedU2,attr"`
	RatedSAttr                            float64                  `xml:"ratedS,attr,omitempty"`
	RatioTapChanger                       *RatioTapChanger         `xml:"ratioTapChanger"`
	PhaseTapChanger                       *PhaseTapChanger         `xml:"phaseTapChanger"`
	OperationalLimitsGroup1               []OperationalLimitsGroup `xml:"operationalLimitsGroup1"`
	OperationalLimitsGroup2               []OperationalLimitsGroup `xml:"operationalLimitsGroup2"`
	*Branch
}

// ThreeWindingsTransformer ...
type ThreeWindingsTransformer struct {
	SelectedOperationalLimitsGroupId1Attr string                   `xml:"selectedOperationalLimitsGroupId1,attr,omitempty"`
	SelectedOperationalLimitsGroupId2Attr string                   `xml:"selectedOperationalLimitsGroupId2,attr,omitempty"`
	SelectedOperationalLimitsGroupId3Attr string                   `xml:"selectedOperationalLimitsGroupId3,attr,omitempty"`
	RatedU0Attr                           float64                  `xml:"ratedU0,attr"`
	RatedU1Attr                           float64                  `xml:"ratedU1,attr"`
	RatedU2Attr                           float64                  `xml:"ratedU2,attr"`
	RatedU3Attr                           float64                  `xml:"ratedU3,attr"`
	RatedS1Attr                           float64                  `xml:"ratedS1,attr,omitempty"`
	RatedS2Attr                           float64                  `xml:"ratedS2,attr,omitempty"`
	RatedS3Attr                           float64                  `xml:"ratedS3,attr,omitempty"`
	R1Attr                                float64                  `xml:"r1,attr"`
	R2Attr                                float64                  `xml:"r2,attr"`
	R3Attr                                float64                  `xml:"r3,attr"`
	X1Attr                                float64                  `xml:"x1,attr"`
	X2Attr                                float64                  `xml:"x2,attr"`
	X3Attr                                float64                  `xml:"x3,attr"`
	G1Attr                                float64                  `xml:"g1,attr"`
	G2Attr                                float64                  `xml:"g2,attr"`
	G3Attr                                float64                  `xml:"g3,attr"`
	B1Attr                                float64                  `xml:"b1,attr"`
	B2Attr                                float64                  `xml:"b2,attr"`
	B3Attr                                float64                  `xml:"b3,attr"`
	Node1Attr                             int                      `xml:"node1,attr"`
	Bus1Attr                              string                   `xml:"bus1,attr,omitempty"`
	VoltageLevelId1Attr                   string                   `xml:"voltageLevelId1,attr"`
	ConnectableBus1Attr                   string                   `xml:"connectableBus1,attr,omitempty"`
	Node2Attr                             int                      `xml:"node2,attr"`
	Bus2Attr                              string                   `xml:"bus2,attr,omitempty"`
	ConnectableBus2Attr                   string                   `xml:"connectableBus2,attr,omitempty"`
	VoltageLevelId2Attr                   string                   `xml:"voltageLevelId2,attr"`
	Node3Attr                             int                      `xml:"node3,attr"`
	Bus3Attr                              string                   `xml:"bus3,attr,omitempty"`
	ConnectableBus3Attr                   string                   `xml:"connectableBus3,attr,omitempty"`
	VoltageLevelId3Attr                   string                   `xml:"voltageLevelId3,attr"`
	P1Attr                                float64                  `xml:"p1,attr,omitempty"`
	Q1Attr                                float64                  `xml:"q1,attr,omitempty"`
	P2Attr                                float64                  `xml:"p2,attr,omitempty"`
	Q2Attr                                float64                  `xml:"q2,attr,omitempty"`
	P3Attr                                float64                  `xml:"p3,attr,omitempty"`
	Q3Attr                                float64                  `xml:"q3,attr,omitempty"`
	RatioTapChanger1                      *RatioTapChanger         `xml:"ratioTapChanger1"`
	PhaseTapChanger1                      *PhaseTapChanger         `xml:"phaseTapChanger1"`
	RatioTapChanger2                      *RatioTapChanger         `xml:"ratioTapChanger2"`
	PhaseTapChanger2                      *PhaseTapChanger         `xml:"phaseTapChanger2"`
	RatioTapChanger3                      *RatioTapChanger         `xml:"ratioTapChanger3"`
	PhaseTapChanger3                      *PhaseTapChanger         `xml:"phaseTapChanger3"`
	OperationalLimitsGroup1               []OperationalLimitsGroup `xml:"operationalLimitsGroup1"`
	OperationalLimitsGroup2               []OperationalLimitsGroup `xml:"operationalLimitsGroup2"`
	OperationalLimitsGroup3               []OperationalLimitsGroup `xml:"operationalLimitsGroup3"`
	*Identifiable
}

// OverloadManagementSystem ...
type OverloadManagementSystem struct {
	EnabledAttr                      bool                               `xml:"enabled,attr,omitempty"`
	MonitoredElementIdAttr           string                             `xml:"monitoredElementId,attr"`
	SideAttr                         string                             `xml:"side,attr,omitempty"`
	BranchTripping                   []BranchTripping                   `xml:"branchTripping"`
	SwitchTripping                   []SwitchTripping                   `xml:"switchTripping"`
	ThreeWindingsTransformerTripping []ThreeWindingsTransformerTripping `xml:"threeWindingsTransformerTripping"`
	*Identifiable
}

// AcDcConverterControlMode ...
type AcDcConverterControlMode string

// DroopCurve ...
type DroopCurve struct {
	Segment []DroopCurveSegment `xml:"segment"`
}

// DroopCurveSegment ...
type DroopCurveSegment struct {
	MinVAttr float64 `xml:"minV,attr"`
	MaxVAttr float64 `xml:"maxV,attr"`
	KAttr    float64 `xml:"k,attr"`
}

// AcDcConverter ...
type AcDcConverter struct {
	DcNode1Attr         string       `xml:"dcNode1,attr"`
	DcConnected1Attr    bool         `xml:"dcConnected1,attr"`
	DcNode2Attr         string       `xml:"dcNode2,attr"`
	DcConnected2Attr    bool         `xml:"dcConnected2,attr"`
	IdleLossAttr        float64      `xml:"idleLoss,attr"`
	SwitchingLossAttr   float64      `xml:"switchingLoss,attr"`
	ResistiveLossAttr   float64      `xml:"resistiveLoss,attr"`
	ControlModeAttr     string       `xml:"controlMode,attr"`
	TargetPAttr         float64      `xml:"targetP,attr,omitempty"`
	TargetVdcAttr       float64      `xml:"targetVdc,attr,omitempty"`
	Node1Attr           int          `xml:"node1,attr"`
	Bus1Attr            string       `xml:"bus1,attr,omitempty"`
	ConnectableBus1Attr string       `xml:"connectableBus1,attr,omitempty"`
	Node2Attr           int          `xml:"node2,attr"`
	Bus2Attr            string       `xml:"bus2,attr,omitempty"`
	ConnectableBus2Attr string       `xml:"connectableBus2,attr,omitempty"`
	P1Attr              float64      `xml:"p1,attr,omitempty"`
	Q1Attr              float64      `xml:"q1,attr,omitempty"`
	P2Attr              float64      `xml:"p2,attr,omitempty"`
	Q2Attr              float64      `xml:"q2,attr,omitempty"`
	DcP1Attr            float64      `xml:"dcP1,attr,omitempty"`
	DcI1Attr            float64      `xml:"dcI1,attr,omitempty"`
	DcP2Attr            float64      `xml:"dcP2,attr,omitempty"`
	DcI2Attr            float64      `xml:"dcI2,attr,omitempty"`
	PccTerminal         *TerminalRef `xml:"pccTerminal"`
	DroopCurve          *DroopCurve  `xml:"droopCurve"`
	*Identifiable
}

// LineCommutatedConverterReactiveModel ...
type LineCommutatedConverterReactiveModel string

// LineCommutatedConverter ...
type LineCommutatedConverter struct {
	ReactiveModelAttr string  `xml:"reactiveModel,attr"`
	PowerFactorAttr   float64 `xml:"powerFactor,attr"`
	*AcDcConverter
}

// VoltageSourceConverter ...
type VoltageSourceConverter struct {
	VoltageRegulatorOnAttr    bool                     `xml:"voltageRegulatorOn,attr"`
	VoltageSetpointAttr       float64                  `xml:"voltageSetpoint,attr,omitempty"`
	ReactivePowerSetpointAttr float64                  `xml:"reactivePowerSetpoint,attr,omitempty"`
	ReactiveCapabilityCurve   *ReactiveCapabilityCurve `xml:"reactiveCapabilityCurve"`
	MinMaxReactiveLimits      *MinMaxReactiveLimits    `xml:"minMaxReactiveLimits"`
	*AcDcConverter
}

// Tripping ...
type Tripping struct {
	KeyAttr          string  `xml:"key,attr"`
	NameAttr         string  `xml:"name,attr,omitempty"`
	CurrentLimitAttr float64 `xml:"currentLimit,attr"`
	OpenActionAttr   bool    `xml:"openAction,attr"`
}

// BranchTripping ...
type BranchTripping struct {
	BranchIdAttr string `xml:"branchId,attr"`
	SideAttr     string `xml:"side,attr,omitempty"`
	*Tripping
}

// SwitchTripping ...
type SwitchTripping struct {
	SwitchIdAttr string `xml:"switchId,attr"`
	*Tripping
}

// ThreeWindingsTransformerTripping ...
type ThreeWindingsTransformerTripping struct {
	ThreeWindingsTransformerIdAttr string `xml:"threeWindingsTransformerId,attr"`
	SideAttr                       string `xml:"side,attr,omitempty"`
	*Tripping
}

// Side ...
type Side string

// TerminalNumber ...
type TerminalNumber string

// TerminalRef ...
type TerminalRef struct {
	IdAttr     string `xml:"id,attr"`
	SideAttr   string `xml:"side,attr,omitempty"`
	NumberAttr string `xml:"number,attr,omitempty"`
}

// RatioTapChangerStep ...
type RatioTapChangerStep struct {
	RhoAttr float64 `xml:"rho,attr"`
	RAttr   float64 `xml:"r,attr"`
	XAttr   float64 `xml:"x,attr"`
	GAttr   float64 `xml:"g,attr"`
	BAttr   float64 `xml:"b,attr"`
}

// PhaseTapChangerStep ...
type PhaseTapChangerStep struct {
	RhoAttr   float64 `xml:"rho,attr"`
	AlphaAttr float64 `xml:"alpha,attr"`
	RAttr     float64 `xml:"r,attr"`
	XAttr     float64 `xml:"x,attr"`
	GAttr     float64 `xml:"g,attr"`
	BAttr     float64 `xml:"b,attr"`
}

// RatioRegulationMode ...
type RatioRegulationMode string

// RatioTapChanger ...
type RatioTapChanger struct {
	LowTapPositionAttr              int                   `xml:"lowTapPosition,attr"`
	TapPositionAttr                 int                   `xml:"tapPosition,attr"`
	SolvedTapPositionAttr           int                   `xml:"solvedTapPosition,attr,omitempty"`
	TargetDeadbandAttr              float64               `xml:"targetDeadband,attr,omitempty"`
	LoadTapChangingCapabilitiesAttr bool                  `xml:"loadTapChangingCapabilities,attr"`
	RegulatingAttr                  bool                  `xml:"regulating,attr,omitempty"`
	RegulationModeAttr              string                `xml:"regulationMode,attr,omitempty"`
	RegulationValueAttr             float64               `xml:"regulationValue,attr,omitempty"`
	TerminalRef                     *TerminalRef          `xml:"terminalRef"`
	Step                            []RatioTapChangerStep `xml:"step"`
}

// PhaseRegulationMode ...
type PhaseRegulationMode string

// PhaseTapChanger ...
type PhaseTapChanger struct {
	LowTapPositionAttr              int                   `xml:"lowTapPosition,attr"`
	TapPositionAttr                 int                   `xml:"tapPosition,attr"`
	SolvedTapPositionAttr           int                   `xml:"solvedTapPosition,attr,omitempty"`
	TargetDeadbandAttr              float64               `xml:"targetDeadband,attr,omitempty"`
	LoadTapChangingCapabilitiesAttr bool                  `xml:"loadTapChangingCapabilities,attr"`
	RegulationModeAttr              string                `xml:"regulationMode,attr"`
	RegulationValueAttr             float64               `xml:"regulationValue,attr,omitempty"`
	RegulatingAttr                  bool                  `xml:"regulating,attr,omitempty"`
	TerminalRef                     *TerminalRef          `xml:"terminalRef"`
	Step                            []PhaseTapChangerStep `xml:"step"`
}

// Line ...
type Line struct {
	SelectedOperationalLimitsGroupId1Attr string                   `xml:"selectedOperationalLimitsGroupId1,attr,omitempty"`
	SelectedOperationalLimitsGroupId2Attr string                   `xml:"selectedOperationalLimitsGroupId2,attr,omitempty"`
	RAttr                                 float64                  `xml:"r,attr"`
	XAttr                                 float64                  `xml:"x,attr"`
	G1Attr                                float64                  `xml:"g1,attr"`
	G2Attr                                float64                  `xml:"g2,attr"`
	B1Attr                                float64                  `xml:"b1,attr"`
	B2Attr                                float64                  `xml:"b2,attr"`
	OperationalLimitsGroup1               []OperationalLimitsGroup `xml:"operationalLimitsGroup1"`
	OperationalLimitsGroup2               []OperationalLimitsGroup `xml:"operationalLimitsGroup2"`
	*Branch
}

// TieLine ...
type TieLine struct {
	DanglingLineId1Attr string `xml:"danglingLineId1,attr"`
	DanglingLineId2Attr string `xml:"danglingLineId2,attr"`
	*Identifiable
}

// ConvertersMode ...
type ConvertersMode string

// HvdcConverterStation ...
type HvdcConverterStation struct {
	LossFactorAttr float32 `xml:"lossFactor,attr"`
	*Injection
}

// VscConverterStation ...
type VscConverterStation struct {
	VoltageRegulatorOnAttr    bool                     `xml:"voltageRegulatorOn,attr"`
	VoltageSetpointAttr       float64                  `xml:"voltageSetpoint,attr,omitempty"`
	ReactivePowerSetpointAttr float64                  `xml:"reactivePowerSetpoint,attr,omitempty"`
	ReactiveCapabilityCurve   *ReactiveCapabilityCurve `xml:"reactiveCapabilityCurve"`
	MinMaxReactiveLimits      *MinMaxReactiveLimits    `xml:"minMaxReactiveLimits"`
	RegulatingTerminal        *TerminalRef             `xml:"regulatingTerminal"`
	*HvdcConverterStation
}

// LccConverterStation ...
type LccConverterStation struct {
	PowerFactorAttr float32 `xml:"powerFactor,attr"`
	*HvdcConverterStation
}

// HvdcLine ...
type HvdcLine struct {
	RAttr                   float64 `xml:"r,attr"`
	NominalVAttr            float64 `xml:"nominalV,attr"`
	ActivePowerSetpointAttr float64 `xml:"activePowerSetpoint,attr"`
	MaxPAttr                float64 `xml:"maxP,attr"`
	ConvertersModeAttr      string  `xml:"convertersMode,attr"`
	ConverterStation1Attr   string  `xml:"converterStation1,attr"`
	ConverterStation2Attr   string  `xml:"converterStation2,attr"`
	*Identifiable
}

// VoltageAngleLimit ...
type VoltageAngleLimit struct {
	IdAttr        string       `xml:"id,attr"`
	HighLimitAttr float64      `xml:"highLimit,attr,omitempty"`
	LowLimitAttr  float64      `xml:"lowLimit,attr,omitempty"`
	From          *TerminalRef `xml:"from"`
	To            *TerminalRef `xml:"to"`
}

// Ground ...
type Ground struct {
	*Injection
}

// VoltageLevelRef ...
type VoltageLevelRef struct {
	IdAttr string `xml:"id,attr"`
}

// AreaBoundary ...
type AreaBoundary struct {
	TypeAttr string `xml:"type,attr"`
	IdAttr   string `xml:"id,attr"`
	SideAttr string `xml:"side,attr,omitempty"`
	AcAttr   bool   `xml:"ac,attr"`
}

// Area ...
type Area struct {
	AreaTypeAttr          string            `xml:"areaType,attr"`
	InterchangeTargetAttr float64           `xml:"interchangeTarget,attr,omitempty"`
	VoltageLevelRef       []VoltageLevelRef `xml:"voltageLevelRef"`
	AreaBoundary          []AreaBoundary    `xml:"areaBoundary"`
	*Identifiable
}

// DcNode ...
type DcNode struct {
	NominalVAttr float64 `xml:"nominalV,attr"`
	VAttr        float64 `xml:"v,attr,omitempty"`
	*Identifiable
}

// DcGround ...
type DcGround struct {
	DcNodeAttr    string  `xml:"dcNode,attr"`
	RAttr         float64 `xml:"r,attr"`
	ConnectedAttr bool    `xml:"connected,attr"`
	DcPAttr       float64 `xml:"dcP,attr,omitempty"`
	DcIAttr       float64 `xml:"dcI,attr,omitempty"`
	*Identifiable
}

// DcLine ...
type DcLine struct {
	DcNode1Attr    string  `xml:"dcNode1,attr"`
	DcNode2Attr    string  `xml:"dcNode2,attr"`
	RAttr          float64 `xml:"r,attr"`
	Connected1Attr bool    `xml:"connected1,attr"`
	Connected2Attr bool    `xml:"connected2,attr"`
	DcP1Attr       float64 `xml:"dcP1,attr,omitempty"`
	DcI1Attr       float64 `xml:"dcI1,attr,omitempty"`
	DcP2Attr       float64 `xml:"dcP2,attr,omitempty"`
	DcI2Attr       float64 `xml:"dcI2,attr,omitempty"`
	*Identifiable
}

// DcSwitchKind ...
type DcSwitchKind string

// DcSwitch ...
type DcSwitch struct {
	DcNode1Attr string `xml:"dcNode1,attr"`
	DcNode2Attr string `xml:"dcNode2,attr"`
	KindAttr    string `xml:"kind,attr"`
	OpenAttr    bool   `xml:"open,attr"`
	*Identifiable
}
